// Code generated by protoc-gen-go. DO NOT EDIT.
// source: node.proto

package node

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Status int32

const (
	Status_SUCCESSFUL Status = 0
	Status_FAILED     Status = 1
)

var Status_name = map[int32]string{
	0: "SUCCESSFUL",
	1: "FAILED",
}

var Status_value = map[string]int32{
	"SUCCESSFUL": 0,
	"FAILED":     1,
}

func (x Status) String() string {
	return proto.EnumName(Status_name, int32(x))
}

func (Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0c843d59d2d938e7, []int{0}
}

type UUID struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UUID) Reset()         { *m = UUID{} }
func (m *UUID) String() string { return proto.CompactTextString(m) }
func (*UUID) ProtoMessage()    {}
func (*UUID) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c843d59d2d938e7, []int{0}
}

func (m *UUID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UUID.Unmarshal(m, b)
}
func (m *UUID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UUID.Marshal(b, m, deterministic)
}
func (m *UUID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UUID.Merge(m, src)
}
func (m *UUID) XXX_Size() int {
	return xxx_messageInfo_UUID.Size(m)
}
func (m *UUID) XXX_DiscardUnknown() {
	xxx_messageInfo_UUID.DiscardUnknown(m)
}

var xxx_messageInfo_UUID proto.InternalMessageInfo

func (m *UUID) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type VmConfig struct {
	VmID                 *UUID    `protobuf:"bytes,1,opt,name=vmID,proto3" json:"vmID,omitempty"`
	Memory               int64    `protobuf:"varint,2,opt,name=memory,proto3" json:"memory,omitempty"`
	Vcpus                int64    `protobuf:"varint,3,opt,name=vcpus,proto3" json:"vcpus,omitempty"`
	KernelImage          string   `protobuf:"bytes,4,opt,name=kernelImage,proto3" json:"kernelImage,omitempty"`
	RootFileSystem       string   `protobuf:"bytes,5,opt,name=rootFileSystem,proto3" json:"rootFileSystem,omitempty"`
	Address              string   `protobuf:"bytes,6,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VmConfig) Reset()         { *m = VmConfig{} }
func (m *VmConfig) String() string { return proto.CompactTextString(m) }
func (*VmConfig) ProtoMessage()    {}
func (*VmConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c843d59d2d938e7, []int{1}
}

func (m *VmConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VmConfig.Unmarshal(m, b)
}
func (m *VmConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VmConfig.Marshal(b, m, deterministic)
}
func (m *VmConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VmConfig.Merge(m, src)
}
func (m *VmConfig) XXX_Size() int {
	return xxx_messageInfo_VmConfig.Size(m)
}
func (m *VmConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_VmConfig.DiscardUnknown(m)
}

var xxx_messageInfo_VmConfig proto.InternalMessageInfo

func (m *VmConfig) GetVmID() *UUID {
	if m != nil {
		return m.VmID
	}
	return nil
}

func (m *VmConfig) GetMemory() int64 {
	if m != nil {
		return m.Memory
	}
	return 0
}

func (m *VmConfig) GetVcpus() int64 {
	if m != nil {
		return m.Vcpus
	}
	return 0
}

func (m *VmConfig) GetKernelImage() string {
	if m != nil {
		return m.KernelImage
	}
	return ""
}

func (m *VmConfig) GetRootFileSystem() string {
	if m != nil {
		return m.RootFileSystem
	}
	return ""
}

func (m *VmConfig) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type Response struct {
	Status               Status    `protobuf:"varint,1,opt,name=status,proto3,enum=node.Status" json:"status,omitempty"`
	Config               *VmConfig `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c843d59d2d938e7, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_SUCCESSFUL
}

func (m *Response) GetConfig() *VmConfig {
	if m != nil {
		return m.Config
	}
	return nil
}

type VmList struct {
	VmID                 []*UUID  `protobuf:"bytes,1,rep,name=vmID,proto3" json:"vmID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VmList) Reset()         { *m = VmList{} }
func (m *VmList) String() string { return proto.CompactTextString(m) }
func (*VmList) ProtoMessage()    {}
func (*VmList) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c843d59d2d938e7, []int{3}
}

func (m *VmList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VmList.Unmarshal(m, b)
}
func (m *VmList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VmList.Marshal(b, m, deterministic)
}
func (m *VmList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VmList.Merge(m, src)
}
func (m *VmList) XXX_Size() int {
	return xxx_messageInfo_VmList.Size(m)
}
func (m *VmList) XXX_DiscardUnknown() {
	xxx_messageInfo_VmList.DiscardUnknown(m)
}

var xxx_messageInfo_VmList proto.InternalMessageInfo

func (m *VmList) GetVmID() []*UUID {
	if m != nil {
		return m.VmID
	}
	return nil
}

type ImageName struct {
	ImageName            string   `protobuf:"bytes,1,opt,name=imageName,proto3" json:"imageName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ImageName) Reset()         { *m = ImageName{} }
func (m *ImageName) String() string { return proto.CompactTextString(m) }
func (*ImageName) ProtoMessage()    {}
func (*ImageName) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c843d59d2d938e7, []int{4}
}

func (m *ImageName) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImageName.Unmarshal(m, b)
}
func (m *ImageName) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImageName.Marshal(b, m, deterministic)
}
func (m *ImageName) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImageName.Merge(m, src)
}
func (m *ImageName) XXX_Size() int {
	return xxx_messageInfo_ImageName.Size(m)
}
func (m *ImageName) XXX_DiscardUnknown() {
	xxx_messageInfo_ImageName.DiscardUnknown(m)
}

var xxx_messageInfo_ImageName proto.InternalMessageInfo

func (m *ImageName) GetImageName() string {
	if m != nil {
		return m.ImageName
	}
	return ""
}

type DriveResponse struct {
	Status               Status   `protobuf:"varint,1,opt,name=status,proto3,enum=node.Status" json:"status,omitempty"`
	Size                 int64    `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DriveResponse) Reset()         { *m = DriveResponse{} }
func (m *DriveResponse) String() string { return proto.CompactTextString(m) }
func (*DriveResponse) ProtoMessage()    {}
func (*DriveResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c843d59d2d938e7, []int{5}
}

func (m *DriveResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DriveResponse.Unmarshal(m, b)
}
func (m *DriveResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DriveResponse.Marshal(b, m, deterministic)
}
func (m *DriveResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DriveResponse.Merge(m, src)
}
func (m *DriveResponse) XXX_Size() int {
	return xxx_messageInfo_DriveResponse.Size(m)
}
func (m *DriveResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DriveResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DriveResponse proto.InternalMessageInfo

func (m *DriveResponse) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_SUCCESSFUL
}

func (m *DriveResponse) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func init() {
	proto.RegisterEnum("node.Status", Status_name, Status_value)
	proto.RegisterType((*UUID)(nil), "node.UUID")
	proto.RegisterType((*VmConfig)(nil), "node.VmConfig")
	proto.RegisterType((*Response)(nil), "node.Response")
	proto.RegisterType((*VmList)(nil), "node.VmList")
	proto.RegisterType((*ImageName)(nil), "node.ImageName")
	proto.RegisterType((*DriveResponse)(nil), "node.DriveResponse")
}

func init() { proto.RegisterFile("node.proto", fileDescriptor_0c843d59d2d938e7) }

var fileDescriptor_0c843d59d2d938e7 = []byte{
	// 433 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0xcf, 0x6a, 0xdb, 0x40,
	0x10, 0xc6, 0xad, 0x5a, 0x91, 0xe3, 0x71, 0xea, 0x86, 0x69, 0x09, 0xc2, 0x0d, 0xc5, 0x2c, 0x21,
	0xb8, 0x2d, 0x28, 0xd4, 0xa5, 0x0f, 0x50, 0xfc, 0x07, 0x04, 0x76, 0x0e, 0x12, 0x16, 0xbd, 0x2a,
	0xf1, 0xc4, 0x88, 0x7a, 0xbd, 0x42, 0xbb, 0x32, 0xb8, 0xcf, 0xd6, 0x6b, 0xdf, 0xab, 0x68, 0x56,
	0x6a, 0xdd, 0xe0, 0x4b, 0x6f, 0xfa, 0xbe, 0xf9, 0xb4, 0x33, 0xf3, 0x63, 0x00, 0x76, 0x6a, 0x4d,
	0x41, 0x5e, 0x28, 0xa3, 0xd0, 0xad, 0xbe, 0x07, 0x6f, 0x37, 0x4a, 0x6d, 0xb6, 0x74, 0xc7, 0xde,
	0x43, 0xf9, 0x74, 0x47, 0x32, 0x37, 0x07, 0x1b, 0x11, 0xd7, 0xe0, 0xae, 0x56, 0xe1, 0x14, 0xdf,
	0xc0, 0xd9, 0x3e, 0xdd, 0x96, 0xe4, 0x3b, 0x43, 0x67, 0xd4, 0x8d, 0xac, 0x10, 0x3f, 0x1d, 0x38,
	0x4f, 0xe4, 0x44, 0xed, 0x9e, 0xb2, 0x0d, 0xbe, 0x03, 0x77, 0x2f, 0xc3, 0x29, 0x27, 0x7a, 0x63,
	0x08, 0xb8, 0x51, 0xf5, 0x73, 0xc4, 0x3e, 0x5e, 0x81, 0x27, 0x49, 0xaa, 0xe2, 0xe0, 0xbf, 0x18,
	0x3a, 0xa3, 0x76, 0x54, 0x2b, 0x7e, 0xfa, 0x31, 0x2f, 0xb5, 0xdf, 0x66, 0xdb, 0x0a, 0x1c, 0x42,
	0xef, 0x3b, 0x15, 0x3b, 0xda, 0x86, 0x32, 0xdd, 0x90, 0xef, 0x72, 0xdb, 0x63, 0x0b, 0x6f, 0xa1,
	0x5f, 0x28, 0x65, 0xe6, 0xd9, 0x96, 0xe2, 0x83, 0x36, 0x24, 0xfd, 0x33, 0x0e, 0x3d, 0x73, 0xd1,
	0x87, 0x4e, 0xba, 0x5e, 0x17, 0xa4, 0xb5, 0xef, 0x71, 0xa0, 0x91, 0xe2, 0x1b, 0x9c, 0x47, 0xa4,
	0x73, 0xb5, 0xd3, 0x84, 0x37, 0xe0, 0x69, 0x93, 0x9a, 0x52, 0xf3, 0xfc, 0xfd, 0xf1, 0x85, 0x9d,
	0x3f, 0x66, 0x2f, 0xaa, 0x6b, 0x78, 0x0b, 0xde, 0x23, 0x6f, 0xcb, 0x3b, 0xf4, 0xc6, 0x7d, 0x9b,
	0x6a, 0x18, 0x44, 0x75, 0x55, 0x8c, 0xc0, 0x4b, 0xe4, 0x22, 0xd3, 0xe6, 0x88, 0x4a, 0xfb, 0x14,
	0x15, 0xf1, 0x1e, 0xba, 0xbc, 0xce, 0x7d, 0x2a, 0x09, 0xaf, 0xa1, 0x9b, 0x35, 0xa2, 0x26, 0xfd,
	0xd7, 0x10, 0x21, 0xbc, 0x9c, 0x16, 0xd9, 0x9e, 0xfe, 0x73, 0x66, 0x04, 0x57, 0x67, 0x3f, 0xa8,
	0xa6, 0xce, 0xdf, 0x1f, 0x6e, 0xc0, 0xb3, 0x29, 0xec, 0x03, 0xc4, 0xab, 0xc9, 0x64, 0x16, 0xc7,
	0xf3, 0xd5, 0xe2, 0xb2, 0x85, 0x00, 0xde, 0xfc, 0x6b, 0xb8, 0x98, 0x4d, 0x2f, 0x9d, 0xf1, 0x2f,
	0x07, 0xdc, 0x7b, 0xb5, 0x26, 0xfc, 0x08, 0x9d, 0xd8, 0xa4, 0x85, 0x49, 0x96, 0xf8, 0x6c, 0xe3,
	0x41, 0xad, 0x9b, 0x99, 0x44, 0xab, 0x62, 0x14, 0x1b, 0x95, 0x27, 0x4b, 0x3c, 0xda, 0xf6, 0x44,
	0xee, 0x13, 0x74, 0x2a, 0x42, 0xc9, 0x52, 0xe3, 0x55, 0x60, 0x6f, 0x30, 0x68, 0x6e, 0x30, 0x98,
	0x55, 0x37, 0x38, 0xb8, 0x68, 0x9a, 0x55, 0x41, 0xd1, 0xc2, 0x2f, 0xd0, 0x9b, 0x14, 0x94, 0x1a,
	0x62, 0x0e, 0xf8, 0xca, 0x96, 0xff, 0xf0, 0x1b, 0xbc, 0xb6, 0xc6, 0x3f, 0x94, 0x44, 0xeb, 0xc1,
	0xe3, 0x67, 0x3f, 0xff, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x3e, 0x08, 0x39, 0xcd, 0xfc, 0x02, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// NodeClient is the client API for Node service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NodeClient interface {
	StartVM(ctx context.Context, in *VmConfig, opts ...grpc.CallOption) (*Response, error)
	StopVM(ctx context.Context, in *UUID, opts ...grpc.CallOption) (*Response, error)
	ListVMs(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*VmList, error)
	CreateDrive(ctx context.Context, in *ImageName, opts ...grpc.CallOption) (*DriveResponse, error)
}

type nodeClient struct {
	cc *grpc.ClientConn
}

func NewNodeClient(cc *grpc.ClientConn) NodeClient {
	return &nodeClient{cc}
}

func (c *nodeClient) StartVM(ctx context.Context, in *VmConfig, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/node.Node/StartVM", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) StopVM(ctx context.Context, in *UUID, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/node.Node/StopVM", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) ListVMs(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*VmList, error) {
	out := new(VmList)
	err := c.cc.Invoke(ctx, "/node.Node/ListVMs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) CreateDrive(ctx context.Context, in *ImageName, opts ...grpc.CallOption) (*DriveResponse, error) {
	out := new(DriveResponse)
	err := c.cc.Invoke(ctx, "/node.Node/CreateDrive", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NodeServer is the server API for Node service.
type NodeServer interface {
	StartVM(context.Context, *VmConfig) (*Response, error)
	StopVM(context.Context, *UUID) (*Response, error)
	ListVMs(context.Context, *empty.Empty) (*VmList, error)
	CreateDrive(context.Context, *ImageName) (*DriveResponse, error)
}

// UnimplementedNodeServer can be embedded to have forward compatible implementations.
type UnimplementedNodeServer struct {
}

func (*UnimplementedNodeServer) StartVM(ctx context.Context, req *VmConfig) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartVM not implemented")
}
func (*UnimplementedNodeServer) StopVM(ctx context.Context, req *UUID) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopVM not implemented")
}
func (*UnimplementedNodeServer) ListVMs(ctx context.Context, req *empty.Empty) (*VmList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListVMs not implemented")
}
func (*UnimplementedNodeServer) CreateDrive(ctx context.Context, req *ImageName) (*DriveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateDrive not implemented")
}

func RegisterNodeServer(s *grpc.Server, srv NodeServer) {
	s.RegisterService(&_Node_serviceDesc, srv)
}

func _Node_StartVM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VmConfig)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).StartVM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/node.Node/StartVM",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).StartVM(ctx, req.(*VmConfig))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_StopVM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UUID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).StopVM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/node.Node/StopVM",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).StopVM(ctx, req.(*UUID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_ListVMs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).ListVMs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/node.Node/ListVMs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).ListVMs(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_CreateDrive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImageName)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).CreateDrive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/node.Node/CreateDrive",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).CreateDrive(ctx, req.(*ImageName))
	}
	return interceptor(ctx, in, info, handler)
}

var _Node_serviceDesc = grpc.ServiceDesc{
	ServiceName: "node.Node",
	HandlerType: (*NodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartVM",
			Handler:    _Node_StartVM_Handler,
		},
		{
			MethodName: "StopVM",
			Handler:    _Node_StopVM_Handler,
		},
		{
			MethodName: "ListVMs",
			Handler:    _Node_ListVMs_Handler,
		},
		{
			MethodName: "CreateDrive",
			Handler:    _Node_CreateDrive_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "node.proto",
}
