- name: clone firectl
  git:
    repo: https://github.com/firecracker-microvm/firectl.git
    dest: src/firectl

- name: check if built
  stat:
    path: ./firectl
  register: firectl


- name: build firectl
  block:
    - shell: make
      args:
        chdir: src/firectl
      environment:
        GOROOT: /usr/local/go
        PATH: "/usr/local/go/bin:{{ ansible_env.PATH }}"

    - copy:
        remote_src: yes
        src: src/firectl/firectl
        dest: $HOME/firectl
  when: not firectl.stat.exists
