// Code generated by protoc-gen-go. DO NOT EDIT.
// source: storage.proto

package storage

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Response_Status int32

const (
	Response_SUCCESS Response_Status = 0
	Response_FAIL    Response_Status = 1
)

var Response_Status_name = map[int32]string{
	0: "SUCCESS",
	1: "FAIL",
}

var Response_Status_value = map[string]int32{
	"SUCCESS": 0,
	"FAIL":    1,
}

func (x Response_Status) String() string {
	return proto.EnumName(Response_Status_name, int32(x))
}

func (Response_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{2, 0}
}

type UUID struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UUID) Reset()         { *m = UUID{} }
func (m *UUID) String() string { return proto.CompactTextString(m) }
func (*UUID) ProtoMessage()    {}
func (*UUID) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{0}
}

func (m *UUID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UUID.Unmarshal(m, b)
}
func (m *UUID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UUID.Marshal(b, m, deterministic)
}
func (m *UUID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UUID.Merge(m, src)
}
func (m *UUID) XXX_Size() int {
	return xxx_messageInfo_UUID.Size(m)
}
func (m *UUID) XXX_DiscardUnknown() {
	xxx_messageInfo_UUID.DiscardUnknown(m)
}

var xxx_messageInfo_UUID proto.InternalMessageInfo

func (m *UUID) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type Volume struct {
	UUID                 string   `protobuf:"bytes,1,opt,name=UUID,proto3" json:"UUID,omitempty"`
	Size                 int64    `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Volume) Reset()         { *m = Volume{} }
func (m *Volume) String() string { return proto.CompactTextString(m) }
func (*Volume) ProtoMessage()    {}
func (*Volume) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{1}
}

func (m *Volume) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Volume.Unmarshal(m, b)
}
func (m *Volume) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Volume.Marshal(b, m, deterministic)
}
func (m *Volume) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Volume.Merge(m, src)
}
func (m *Volume) XXX_Size() int {
	return xxx_messageInfo_Volume.Size(m)
}
func (m *Volume) XXX_DiscardUnknown() {
	xxx_messageInfo_Volume.DiscardUnknown(m)
}

var xxx_messageInfo_Volume proto.InternalMessageInfo

func (m *Volume) GetUUID() string {
	if m != nil {
		return m.UUID
	}
	return ""
}

<<<<<<< HEAD
func (m *Volume) GetSize() int64 {
=======
func (m *Volume) GetSize() int32 {
>>>>>>> Creating works!
	if m != nil {
		return m.Size
	}
	return 0
}

type Response struct {
	Status               Response_Status `protobuf:"varint,1,opt,name=status,proto3,enum=storage.Response_Status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetStatus() Response_Status {
	if m != nil {
		return m.Status
	}
	return Response_SUCCESS
}

type VolumeList struct {
	Volumes              []*Volume `protobuf:"bytes,1,rep,name=volumes,proto3" json:"volumes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *VolumeList) Reset()         { *m = VolumeList{} }
func (m *VolumeList) String() string { return proto.CompactTextString(m) }
func (*VolumeList) ProtoMessage()    {}
func (*VolumeList) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{3}
}

func (m *VolumeList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VolumeList.Unmarshal(m, b)
}
func (m *VolumeList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VolumeList.Marshal(b, m, deterministic)
}
func (m *VolumeList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VolumeList.Merge(m, src)
}
func (m *VolumeList) XXX_Size() int {
	return xxx_messageInfo_VolumeList.Size(m)
}
func (m *VolumeList) XXX_DiscardUnknown() {
	xxx_messageInfo_VolumeList.DiscardUnknown(m)
}

var xxx_messageInfo_VolumeList proto.InternalMessageInfo

func (m *VolumeList) GetVolumes() []*Volume {
	if m != nil {
		return m.Volumes
	}
	return nil
}

func init() {
	proto.RegisterEnum("storage.Response_Status", Response_Status_name, Response_Status_value)
	proto.RegisterType((*UUID)(nil), "storage.UUID")
	proto.RegisterType((*Volume)(nil), "storage.Volume")
	proto.RegisterType((*Response)(nil), "storage.Response")
	proto.RegisterType((*VolumeList)(nil), "storage.VolumeList")
}

func init() { proto.RegisterFile("storage.proto", fileDescriptor_0d2c4ccf1453ffdb) }

var fileDescriptor_0d2c4ccf1453ffdb = []byte{
	// 287 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x41, 0x4b, 0xc3, 0x40,
<<<<<<< HEAD
	0x14, 0x84, 0x1b, 0x1b, 0x37, 0xf5, 0x95, 0x6a, 0x7d, 0x8a, 0x94, 0x2a, 0x58, 0xf6, 0x54, 0x41,
=======
	0x14, 0x84, 0x1b, 0x4d, 0x37, 0xf5, 0x95, 0x6a, 0x7d, 0x8a, 0x94, 0x2a, 0x58, 0xf6, 0x54, 0x41,
>>>>>>> Creating works!
	0xb6, 0xa5, 0x22, 0x9e, 0xa5, 0x56, 0x28, 0xf4, 0xb4, 0x21, 0xde, 0x3c, 0xa4, 0xf0, 0x0c, 0x85,
	0xc4, 0x0d, 0xd9, 0x4d, 0x40, 0x7f, 0x8c, 0xbf, 0x55, 0xb2, 0x9b, 0xf4, 0x50, 0xbd, 0xed, 0xec,
	0x7c, 0x8f, 0x19, 0x06, 0x06, 0xda, 0xa8, 0x22, 0x4e, 0x48, 0xe4, 0x85, 0x32, 0x0a, 0x83, 0x46,
	0x8e, 0xaf, 0x13, 0xa5, 0x92, 0x94, 0x66, 0xf6, 0x7b, 0x5b, 0x7e, 0xcc, 0x28, 0xcb, 0xcd, 0x97,
<<<<<<< HEAD
	0xa3, 0xf8, 0x0d, 0xf8, 0x51, 0xb4, 0x7e, 0xc1, 0x4b, 0x38, 0xae, 0xe2, 0xb4, 0xa4, 0x91, 0x37,
	0xf1, 0xa6, 0x27, 0xd2, 0x09, 0x3e, 0x07, 0xf6, 0xa6, 0xd2, 0x32, 0x23, 0x44, 0xc7, 0x35, 0xb6,
	0xbb, 0x41, 0xf0, 0xf5, 0xee, 0x9b, 0x46, 0x47, 0x13, 0x6f, 0xda, 0x95, 0xf6, 0xcd, 0xdf, 0xa1,
	0x27, 0x49, 0xe7, 0xea, 0x53, 0x13, 0xce, 0x81, 0x69, 0x13, 0x9b, 0x52, 0xdb, 0xab, 0xd3, 0xc5,
	0x48, 0xb4, 0x0d, 0x5b, 0x44, 0x84, 0xd6, 0x97, 0x0d, 0xc7, 0x6f, 0x81, 0xb9, 0x1f, 0xec, 0x43,
	0x10, 0x46, 0xcb, 0xe5, 0x2a, 0x0c, 0x87, 0x1d, 0xec, 0x81, 0xff, 0xfa, 0xbc, 0xde, 0x0c, 0x3d,
	0xfe, 0x04, 0xe0, 0x0a, 0x6d, 0x76, 0xda, 0xe0, 0x1d, 0x04, 0x95, 0x55, 0x75, 0x42, 0x77, 0xda,
=======
	0xa3, 0xf8, 0x0d, 0xf8, 0x51, 0xb4, 0x7e, 0xc1, 0x4b, 0xe8, 0x56, 0x71, 0x5a, 0xd2, 0xc8, 0x9b,
	0x78, 0xd3, 0x13, 0xe9, 0x04, 0x9f, 0x03, 0x7b, 0x53, 0x69, 0x99, 0x11, 0xa2, 0xe3, 0x1a, 0xdb,
	0xdd, 0x20, 0xf8, 0x7a, 0xf7, 0x4d, 0xa3, 0xa3, 0x89, 0x37, 0xed, 0x4a, 0xfb, 0xe6, 0xef, 0xd0,
	0x93, 0xa4, 0x73, 0xf5, 0xa9, 0x09, 0xe7, 0xc0, 0xb4, 0x89, 0x4d, 0xa9, 0xed, 0xd5, 0xe9, 0x62,
	0x24, 0xda, 0x86, 0x2d, 0x22, 0x42, 0xeb, 0xcb, 0x86, 0xe3, 0xb7, 0xc0, 0xdc, 0x0f, 0xf6, 0x21,
	0x08, 0xa3, 0xe5, 0x72, 0x15, 0x86, 0xc3, 0x0e, 0xf6, 0xc0, 0x7f, 0x7d, 0x5e, 0x6f, 0x86, 0x1e,
	0x7f, 0x02, 0x70, 0x85, 0x36, 0x3b, 0x6d, 0xf0, 0x0e, 0x82, 0xca, 0xaa, 0x3a, 0xe1, 0x78, 0xda,
>>>>>>> Creating works!
	0x5f, 0x9c, 0xed, 0x13, 0x1c, 0x25, 0x5b, 0x7f, 0xf1, 0xe3, 0x41, 0x10, 0x3a, 0x0f, 0x05, 0xb0,
	0x65, 0x41, 0xb1, 0x21, 0x3c, 0xe4, 0xc7, 0xe7, 0x7f, 0x2a, 0xf2, 0x0e, 0xde, 0x03, 0x93, 0x94,
	0xa9, 0x8a, 0x70, 0xb0, 0xb7, 0xeb, 0x01, 0xfe, 0xa7, 0x1f, 0xc1, 0xb7, 0xe5, 0xae, 0x84, 0xdb,
	0x5d, 0xb4, 0xbb, 0x8b, 0x55, 0xbd, 0xfb, 0xf8, 0xe2, 0x20, 0xb3, 0x86, 0x79, 0x67, 0xcb, 0x2c,
<<<<<<< HEAD
	0xf6, 0xf0, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x36, 0xe8, 0x21, 0x9d, 0xc6, 0x01, 0x00, 0x00,
=======
	0xf6, 0xf0, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x2c, 0x3d, 0x6b, 0xd4, 0xc6, 0x01, 0x00, 0x00,
>>>>>>> Creating works!
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StorageClient is the client API for Storage service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StorageClient interface {
	Create(ctx context.Context, in *Volume, opts ...grpc.CallOption) (*Response, error)
	Remove(ctx context.Context, in *UUID, opts ...grpc.CallOption) (*Response, error)
	List(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*VolumeList, error)
}

type storageClient struct {
	cc *grpc.ClientConn
}

func NewStorageClient(cc *grpc.ClientConn) StorageClient {
	return &storageClient{cc}
}

func (c *storageClient) Create(ctx context.Context, in *Volume, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/storage.Storage/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageClient) Remove(ctx context.Context, in *UUID, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/storage.Storage/Remove", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageClient) List(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*VolumeList, error) {
	out := new(VolumeList)
	err := c.cc.Invoke(ctx, "/storage.Storage/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StorageServer is the server API for Storage service.
type StorageServer interface {
	Create(context.Context, *Volume) (*Response, error)
	Remove(context.Context, *UUID) (*Response, error)
	List(context.Context, *empty.Empty) (*VolumeList, error)
}

// UnimplementedStorageServer can be embedded to have forward compatible implementations.
type UnimplementedStorageServer struct {
}

func (*UnimplementedStorageServer) Create(ctx context.Context, req *Volume) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedStorageServer) Remove(ctx context.Context, req *UUID) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Remove not implemented")
}
func (*UnimplementedStorageServer) List(ctx context.Context, req *empty.Empty) (*VolumeList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}

func RegisterStorageServer(s *grpc.Server, srv StorageServer) {
	s.RegisterService(&_Storage_serviceDesc, srv)
}

func _Storage_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Volume)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/storage.Storage/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServer).Create(ctx, req.(*Volume))
	}
	return interceptor(ctx, in, info, handler)
}

func _Storage_Remove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UUID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServer).Remove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/storage.Storage/Remove",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServer).Remove(ctx, req.(*UUID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Storage_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/storage.Storage/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServer).List(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Storage_serviceDesc = grpc.ServiceDesc{
	ServiceName: "storage.Storage",
	HandlerType: (*StorageServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Storage_Create_Handler,
		},
		{
			MethodName: "Remove",
			Handler:    _Storage_Remove_Handler,
		},
		{
			MethodName: "List",
			Handler:    _Storage_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "storage.proto",
}
